# Generated by Django 6.0 on 2026-02-04 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Militar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('graduacao', models.CharField(choices=[('SD', 'Soldado'), ('CB', 'Cabo'), ('3SG', '3º Sargento'), ('2SG', '2º Sargento'), ('1SG', '1º Sargento'), ('ST', 'Subtenente'), ('ASP', 'Aspirante'), ('2TEN', '2º Tenente'), ('1TEN', '1º Tenente'), ('CAP', 'Capitão'), ('MAJ', 'Major'), ('TC', 'Tenente-Coronel'), ('CEL', 'Coronel'), ('GEN', 'General')], max_length=20)),
                ('subunidade', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Afastamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FERIAS', 'Férias'), ('LICENCA', 'Licença'), ('DISPENSA', 'Dispensa'), ('MEDICA', 'Dispensa Médica')], max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('militar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afastamentos', to='core.militar')),
            ],
            options={
                'verbose_name': 'Afastamento',
                'verbose_name_plural': 'Afastamentos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('militar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='core.militar')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['-data'],
                'unique_together': {('militar', 'data')},
            },
        ),
    ]
