# Generated by Django 6.0 on 2025-12-25 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afastamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('militar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afastamentos', to='core.militar')),
            ],
        ),
    ]
