# Generated by Django 6.0 on 2026-02-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_tipo_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='tipo',
            field=models.CharField(choices=[('GUARDA', 'Guarda ao Quartel'), ('PLANTAO', 'Plantão'), ('PERMANENCIA', 'Permanência'), ('COMANDANTE_GUARDA', 'Comandante da Guarda'), ('CABO_GUARDA', 'Cabo da Guarda'), ('ADJUNTO', 'Adjunto'), ('OFICIAL_DIA', 'Oficial de Dia')], default='GUARDA', max_length=20),
        ),
    ]
