# Generated by Django 6.0.2 on 2026-02-10 23:13

from django.conf import settings
from django.db import migrations, models

def dedup_special_roles(apps, schema_editor):
    Servico = apps.get_model('core', 'Servico')
    especiais = ['OFICIAL_DIA', 'ADJUNTO', 'COMANDANTE_GUARDA', 'CABO_GUARDA']
    seen = {}
    for s in Servico.objects.filter(tipo__in=especiais).order_by('data', 'tipo', 'id'):
        key = (s.data, s.tipo)
        if key in seen:
            # Delete duplicates, keep the first occurrence
            s.delete()
        else:
            seen[key] = s.id


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_servico_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(dedup_special_roles, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='servico',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo__in', ['OFICIAL_DIA', 'ADJUNTO', 'COMANDANTE_GUARDA', 'CABO_GUARDA'])), fields=('data', 'tipo'), name='unique_special_role_per_day'),
        ),
    ]
