# Generated by Django 6.0.2 on 2026-02-11 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servico_unique_special_role_per_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='servico',
            name='unique_special_role_per_day',
        ),
        migrations.AlterField(
            model_name='servico',
            name='tipo',
            field=models.CharField(choices=[('GUARDA', 'Guarda ao Quartel'), ('PLANTAO', 'Plantão'), ('PERMANENCIA', 'Permanência'), ('COMANDANTE_GUARDA', 'Comandante da Guarda'), ('CABO_GUARDA', 'Cabo da Guarda'), ('CABO_DIA', 'Cabo de Dia'), ('ADJUNTO', 'Adjunto'), ('OFICIAL_DIA', 'Oficial de Dia')], default='GUARDA', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='servico',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo__in', ['OFICIAL_DIA', 'ADJUNTO', 'COMANDANTE_GUARDA', 'CABO_GUARDA', 'CABO_DIA'])), fields=('data', 'tipo'), name='unique_special_role_per_day'),
        ),
    ]
